server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**

        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auth/**

        - id: exchange
          uri: http://exchange:80
          predicates:
            - Path=/exchange/**
        
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/product/**
        
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/order/**
        

logging:
  level:
    store: ${LOGGING_LEVEL_STORE:debug}